import bcrypt from 'bcryptjs';
import {
  Company,
  User,
  Role,
  Permission,
  TaskStatus,
  TaskPriority,
  CustomField,
  Task,
  CompanyFile,
  TaskTimelineEvent,
  TaskNote,
  TaskAttachment,
  TaskStatusSlug,
  TaskPrioritySlug,
  UserDashboardConfig,
  SystemAboutSettings,
} from '../../types/database';
import { PermissionKey, SYSTEM_PERMISSIONS } from '../../types/permissions';

export interface DatabaseState {
  companies: Company[];
  users: User[];
  roles: Role[];
  permissions: Permission[];
  userRoles: Array<{ id: string; userId: string; roleId: string; companyId?: string | null; createdAt?: string }>;
  rolePermissions: Array<{ id: string; roleId: string; permissionKey: PermissionKey; createdAt?: string }>;
  userCompanies: Array<{ id: string; userId: string; companyId: string; isPrimary: boolean; assignedRoleSlug: string; createdAt?: string }>;
  taskStatuses: TaskStatus[];
  taskPriorities: TaskPriority[];
  tasks: Task[];
  companyFiles: CompanyFile[];
  customFields: CustomField[];
  customFieldValues: any[];
  notifications: any[];
  auditLogs: any[];
  dashboardConfigs: UserDashboardConfig[];
  systemAbout: SystemAboutSettings;
}

export function createInitialDatabaseState(): DatabaseState {
  const salt = bcrypt.genSaltSync(10);
  const superAdminHash = bcrypt.hashSync('7941631', salt);
  const adminHash = bcrypt.hashSync('Admin@2026', salt);
  const managerHash = bcrypt.hashSync('Manager@2026', salt);

  const companies: Company[] = [
    {
      id: 'c1-noor-retail',
      code: 'RET-NOOR',
      nameEn: 'Al-Noor Retail Group',
      nameAr: 'مجموعة النور للتجزئة',
      industryEn: 'Retail & Consumer Goods',
      industryAr: 'التجزئة والسلع الاستهلاكية',
      logoUrl: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=120&h=120&q=80',
      descriptionEn: 'Leading retail chain and omnichannel hypermarkets across Saudi Arabia.',
      descriptionAr: 'سلسلة متاجر تجزئة وهايبر ماركت رائدة تقدم خدمات تسوق متكاملة عبر المملكة العربية السعودية.',
      managerId: 'u2-admin',
      contactEmail: 'operations@alnoor-retail.sa',
      contactPhone: '+966 11 456 7890',
      website: 'https://alnoor-retail.sa',
      address: 'King Fahd Road, Al-Olaya, Riyadh 12211, Saudi Arabia',
      currency: 'IQD',
      country: 'IQ',
      isActive: true,
      isArchived: false,
      settings: { timezone: 'Asia/Riyadh', fiscalYearStart: 'January' },
      createdAt: new Date('2026-01-10').toISOString(),
      updatedAt: new Date('2026-01-10').toISOString(),
    },
    {
      id: 'c2-apex-logistics',
      code: 'LOG-APEX',
      nameEn: 'Apex Logistics & Freight',
      nameAr: 'شركة آبيكس للنقل واللوجستيات',
      industryEn: 'Supply Chain & Logistics',
      industryAr: 'سلاسل الإمداد والشحن',
      logoUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=120&h=120&q=80',
      descriptionEn: 'Cross-border supply chain, cold storage, and maritime freight solutions.',
      descriptionAr: 'حلول سلاسل الإمداد والتخزين المبرد والشحن البحري والجوي الدولي بدول مجلس التعاون.',
      managerId: 'u1-super-admin',
      contactEmail: 'ops@apex-logistics.ae',
      contactPhone: '+971 4 888 1234',
      website: 'https://apexlogistics.ae',
      address: 'Jebel Ali Freezone, South Zone 2, Dubai, UAE',
      currency: 'AED',
      country: 'AE',
      isActive: true,
      isArchived: false,
      settings: { timezone: 'Asia/Dubai', fiscalYearStart: 'January' },
      createdAt: new Date('2026-01-15').toISOString(),
      updatedAt: new Date('2026-01-15').toISOString(),
    },
    {
      id: 'c3-techsphere',
      code: 'TECH-SPHERE',
      nameEn: 'TechSphere Software Solutions',
      nameAr: 'حلول تك سفير للبرمجيات',
      industryEn: 'Information Technology',
      industryAr: 'تقنية المعلومات والبرمجيات',
      logoUrl: 'https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=120&h=120&q=80',
      descriptionEn: 'Enterprise cloud services, AI automation, and custom software engineering.',
      descriptionAr: 'خدمات السحابة المؤسسية والذكاء الاصطناعي وهندسة البرمجيات المتطورة للشركات الكبرى.',
      managerId: 'u2-admin',
      contactEmail: 'contact@techsphere.com',
      contactPhone: '+966 12 654 3210',
      website: 'https://techsphere.sa',
      address: 'Digital City, R&D Hub, Building 4, Riyadh, Saudi Arabia',
      currency: 'USD',
      country: 'SA',
      isActive: true,
      isArchived: false,
      settings: { timezone: 'Asia/Riyadh', fiscalYearStart: 'January' },
      createdAt: new Date('2026-02-01').toISOString(),
      updatedAt: new Date('2026-02-01').toISOString(),
    },
    {
      id: 'c4-horizon-media',
      code: 'MED-HORIZON',
      nameEn: 'Horizon Media & Advertising',
      nameAr: 'مؤسسة هورايزون للإعلام والإعلان',
      industryEn: 'Creative & Digital Media',
      industryAr: 'الإعلام الرقمي والتسويق',
      logoUrl: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?auto=format&fit=crop&w=120&h=120&q=80',
      descriptionEn: 'Full-service advertising, digital marketing, PR campaigns, and media production.',
      descriptionAr: 'وكالة متكاملة للإعلانات والتسويق الرقمي وحملات العلاقات العامة والإنتاج الإعلامي الاحترافي.',
      managerId: 'u3-manager',
      contactEmail: 'hello@horizonmedia.sa',
      contactPhone: '+966 13 890 1122',
      website: 'https://horizonmedia.sa',
      address: 'Al-Khobar Corniche Boulevard, Eastern Province, Saudi Arabia',
      currency: 'IQD',
      country: 'IQ',
      isActive: true,
      isArchived: false,
      settings: { timezone: 'Asia/Riyadh', fiscalYearStart: 'January' },
      createdAt: new Date('2026-02-15').toISOString(),
      updatedAt: new Date('2026-02-15').toISOString(),
    },
    {
      id: 'c5-gulf-capital',
      code: 'RE-GULF',
      nameEn: 'Gulf Horizon Real Estate',
      nameAr: 'شركة أفق الخليج العقارية',
      industryEn: 'Real Estate & Development',
      industryAr: 'التطوير والاستثمار العقاري',
      logoUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=120&h=120&q=80',
      descriptionEn: 'Prime real estate developments, commercial towers, and asset portfolio management.',
      descriptionAr: 'تطوير المشاريع العقارية الفاخرة والأبراج التجارية وإدارة المحافظ العقارية الاستثمارية.',
      managerId: 'u1-super-admin',
      contactEmail: 'invest@gulfhorizonre.com',
      contactPhone: '+965 222 3344',
      website: 'https://gulfhorizonre.com',
      address: 'Sharq Commercial District, Tower 14, Kuwait City, Kuwait',
      currency: 'KWD',
      country: 'KW',
      isActive: true,
      isArchived: false,
      settings: { timezone: 'Asia/Kuwait', fiscalYearStart: 'April' },
      createdAt: new Date('2026-03-01').toISOString(),
      updatedAt: new Date('2026-03-01').toISOString(),
    },
    {
      id: 'c6-al-moneash',
      code: 'AMC-8432',
      nameEn: 'Al-Moneash Trading & Distribution',
      nameAr: 'شركة المنعش العامة',
      industryEn: 'Consumer Goods & Distribution',
      industryAr: 'السلع الاستهلاكية والتوزيع التجاري',
      logoUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=120&h=120&q=80',
      descriptionEn: 'Leading consumer goods distribution, commercial agency, and supply chain across Iraq.',
      descriptionAr: 'شركة المنعش للتجارة العامة وتوزيع المنتجات الاستهلاكية والوكالات التجارية في عموم العراق.',
      managerId: 'u1-super-admin',
      contactEmail: 'info@al-moneash.iq',
      contactPhone: '+964 770 123 4567',
      website: 'https://al-moneash.iq',
      address: 'حي المنصور، تقاطع الرواد، بغداد، العراق',
      currency: 'IQD',
      country: 'IQ',
      isActive: true,
      isArchived: false,
      settings: { timezone: 'Asia/Baghdad', fiscalYearStart: 'January' },
      createdAt: new Date('2026-01-01').toISOString(),
      updatedAt: new Date('2026-01-01').toISOString(),
    },
  ];

  const roles: Role[] = [
    {
      id: 'role-super-admin',
      slug: 'super_admin',
      nameEn: 'Super Admin',
      nameAr: 'مدير عام النظام',
      descriptionEn: 'Full system-wide governance across all companies and permissions',
      descriptionAr: 'حوكمة وصلاحيات شاملة على مستوى النظام وكافة الشركات التابعة',
      isSystem: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'role-admin',
      slug: 'admin',
      nameEn: 'Admin',
      nameAr: 'ادمن',
      descriptionEn: 'Full operational control within assigned companies',
      descriptionAr: 'إدارة تشغيلية وتنظيمية كاملة داخل الشركات المصرح بها',
      isSystem: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'role-manager',
      slug: 'manager_owner',
      nameEn: 'Manager',
      nameAr: 'مدير',
      descriptionEn: 'Departmental management, tasks supervision, and company reports',
      descriptionAr: 'إدارة الأقسام والمهام ومتابعة تقارير الشركة التابعة',
      isSystem: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  const permissions: Permission[] = SYSTEM_PERMISSIONS.map((p, idx) => ({
    id: `perm-${idx + 1}`,
    key: p.key,
    module: p.module,
    nameEn: p.nameEn,
    nameAr: p.nameAr,
    descriptionEn: p.descriptionEn,
    descriptionAr: p.descriptionAr,
    createdAt: new Date().toISOString(),
  }));

  const rolePermissions: Array<{ id: string; roleId: string; permissionKey: PermissionKey }> = [];

  // Super admin: ALL permissions
  permissions.forEach((p, idx) => {
    rolePermissions.push({
      id: `rp-sa-${idx}`,
      roleId: 'role-super-admin',
      permissionKey: p.key,
    });
  });

  // Admin: Specific permissions
  const adminPermKeys = [
    PermissionKey.COMPANIES_VIEW,
    PermissionKey.COMPANIES_EDIT,
    PermissionKey.TASKS_VIEW,
    PermissionKey.TASKS_CREATE,
    PermissionKey.TASKS_EDIT,
    PermissionKey.TASKS_DELETE,
    PermissionKey.TASKS_CHANGE_STATUS,
    PermissionKey.TASKS_ASSIGN,
    PermissionKey.REPORTS_VIEW,
    PermissionKey.REPORTS_EXPORT,
    PermissionKey.USERS_VIEW,
    PermissionKey.USERS_MANAGE,
    PermissionKey.CUSTOM_FIELDS_MANAGE,
    PermissionKey.AUDIT_LOGS_VIEW,
  ];
  adminPermKeys.forEach((key, idx) => {
    rolePermissions.push({
      id: `rp-admin-${idx}`,
      roleId: 'role-admin',
      permissionKey: key,
    });
  });

  // Manager: Subset permissions
  const managerPermKeys = [
    PermissionKey.COMPANIES_VIEW,
    PermissionKey.TASKS_VIEW,
    PermissionKey.TASKS_CREATE,
    PermissionKey.TASKS_EDIT,
    PermissionKey.TASKS_CHANGE_STATUS,
    PermissionKey.REPORTS_VIEW,
  ];
  managerPermKeys.forEach((key, idx) => {
    rolePermissions.push({
      id: `rp-mgr-${idx}`,
      roleId: 'role-manager',
      permissionKey: key,
    });
  });

  const users: User[] = [
    {
      id: 'u1-super-admin',
      email: 'admin@holding.com',
      passwordHash: superAdminHash,
      fullName: 'admin',
      fullNameAr: 'مدير النظام (admin)',
      phone: '+966 50 111 2233',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=120&h=120&q=80',
      isActive: true,
      isArchived: false,
      lastLoginAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'u2-admin',
      email: 'sara.admin@holding.com',
      passwordHash: adminHash,
      fullName: 'Sara Al-Otaibi',
      fullNameAr: 'سارة العتيبي',
      phone: '+966 54 888 7766',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=120&h=120&q=80',
      isActive: true,
      isArchived: false,
      lastLoginAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'u3-manager',
      email: 'manager@holding.com',
      passwordHash: managerHash,
      fullName: 'Faisal Al-Ghamdi',
      fullNameAr: 'فيصل الغامدي',
      phone: '+966 55 444 3322',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&h=120&q=80',
      isActive: true,
      isArchived: false,
      lastLoginAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  const userRoles = [
    { id: 'ur-1', userId: 'u1-super-admin', roleId: 'role-super-admin', companyId: null },
    { id: 'ur-2', userId: 'u2-admin', roleId: 'role-admin', companyId: 'c1-noor-retail' },
    { id: 'ur-3', userId: 'u2-admin', roleId: 'role-admin', companyId: 'c3-techsphere' },
    { id: 'ur-4', userId: 'u3-manager', roleId: 'role-manager', companyId: 'c1-noor-retail' },
  ];

  const userCompanies = [
    { id: 'uc-1', userId: 'u1-super-admin', companyId: 'c1-noor-retail', isPrimary: true, assignedRoleSlug: 'super_admin' },
    { id: 'uc-2', userId: 'u1-super-admin', companyId: 'c2-apex-logistics', isPrimary: false, assignedRoleSlug: 'super_admin' },
    { id: 'uc-3', userId: 'u1-super-admin', companyId: 'c3-techsphere', isPrimary: false, assignedRoleSlug: 'super_admin' },
    { id: 'uc-4', userId: 'u1-super-admin', companyId: 'c4-horizon-media', isPrimary: false, assignedRoleSlug: 'super_admin' },
    { id: 'uc-5', userId: 'u1-super-admin', companyId: 'c5-gulf-capital', isPrimary: false, assignedRoleSlug: 'super_admin' },
    { id: 'uc-6-moneash', userId: 'u1-super-admin', companyId: 'c6-al-moneash', isPrimary: false, assignedRoleSlug: 'super_admin' },

    { id: 'uc-6', userId: 'u2-admin', companyId: 'c1-noor-retail', isPrimary: true, assignedRoleSlug: 'admin' },
    { id: 'uc-7', userId: 'u2-admin', companyId: 'c3-techsphere', isPrimary: false, assignedRoleSlug: 'admin' },
    { id: 'uc-7-moneash', userId: 'u2-admin', companyId: 'c6-al-moneash', isPrimary: false, assignedRoleSlug: 'admin' },

    { id: 'uc-8', userId: 'u3-manager', companyId: 'c1-noor-retail', isPrimary: true, assignedRoleSlug: 'manager_owner' },
    { id: 'uc-8-moneash', userId: 'u3-manager', companyId: 'c6-al-moneash', isPrimary: false, assignedRoleSlug: 'manager_owner' },
  ];

  const taskStatuses: TaskStatus[] = [
    { id: 'ts-pending', slug: 'pending', nameEn: 'Pending', nameAr: 'بانتظار البدء', color: '#64748b', orderIndex: 1, isDefault: true, isFinal: false, createdAt: new Date().toISOString() },
    { id: 'ts-in-progress', slug: 'in_progress', nameEn: 'In Progress', nameAr: 'قيد التنفيذ', color: '#2563eb', orderIndex: 2, isDefault: false, isFinal: false, createdAt: new Date().toISOString() },
    { id: 'ts-delayed', slug: 'delayed', nameEn: 'Delayed', nameAr: 'متأخرة', color: '#ea580c', orderIndex: 3, isDefault: false, isFinal: false, createdAt: new Date().toISOString() },
    { id: 'ts-completed', slug: 'completed', nameEn: 'Completed', nameAr: 'مكتملة', color: '#16a34a', orderIndex: 4, isDefault: false, isFinal: true, createdAt: new Date().toISOString() },
    { id: 'ts-paused', slug: 'paused', nameEn: 'Paused', nameAr: 'معلقة / متوقفة', color: '#d97706', orderIndex: 5, isDefault: false, isFinal: false, createdAt: new Date().toISOString() },
    { id: 'ts-cancelled', slug: 'cancelled', nameEn: 'Cancelled', nameAr: 'ملغاة', color: '#dc2626', orderIndex: 6, isDefault: false, isFinal: true, createdAt: new Date().toISOString() },
    // Compatibility aliases
    { id: 'ts-1', slug: 'pending', nameEn: 'Pending', nameAr: 'بانتظار البدء', color: '#64748b', orderIndex: 1, isDefault: true, isFinal: false, createdAt: new Date().toISOString() },
    { id: 'ts-2', slug: 'in_progress', nameEn: 'In Progress', nameAr: 'قيد التنفيذ', color: '#2563eb', orderIndex: 2, isDefault: false, isFinal: false, createdAt: new Date().toISOString() },
    { id: 'ts-3', slug: 'in_progress', nameEn: 'Review & QA', nameAr: 'المراجعة والتدقيق', color: '#8b5cf6', orderIndex: 3, isDefault: false, isFinal: false, createdAt: new Date().toISOString() },
    { id: 'ts-4', slug: 'delayed', nameEn: 'Paused / Delayed', nameAr: 'معلقة / متأخرة', color: '#ea580c', orderIndex: 4, isDefault: false, isFinal: false, createdAt: new Date().toISOString() },
    { id: 'ts-5', slug: 'completed', nameEn: 'Completed', nameAr: 'مكتملة', color: '#16a34a', orderIndex: 5, isDefault: false, isFinal: true, createdAt: new Date().toISOString() },
  ];

  const taskPriorities: TaskPriority[] = [
    { id: 'tp-vip', slug: 'vip', nameEn: 'VIP', nameAr: 'أولوية قصوى (VIP)', color: '#dc2626', orderIndex: 1, createdAt: new Date().toISOString() },
    { id: 'tp-high', slug: 'high', nameEn: 'High', nameAr: 'مرتفعة', color: '#ea580c', orderIndex: 2, createdAt: new Date().toISOString() },
    { id: 'tp-medium', slug: 'medium', nameEn: 'Medium', nameAr: 'متوسطة', color: '#0284c7', orderIndex: 3, createdAt: new Date().toISOString() },
    { id: 'tp-low', slug: 'low', nameEn: 'Low', nameAr: 'منخفضة', color: '#64748b', orderIndex: 4, createdAt: new Date().toISOString() },
    // Compatibility aliases
    { id: 'tp-1', slug: 'low', nameEn: 'Low', nameAr: 'منخفضة', color: '#64748b', orderIndex: 4, createdAt: new Date().toISOString() },
    { id: 'tp-2', slug: 'medium', nameEn: 'Medium', nameAr: 'متوسطة', color: '#0284c7', orderIndex: 3, createdAt: new Date().toISOString() },
    { id: 'tp-3', slug: 'high', nameEn: 'High', nameAr: 'عالية', color: '#ea580c', orderIndex: 2, createdAt: new Date().toISOString() },
    { id: 'tp-4', slug: 'vip', nameEn: 'VIP & Critical', nameAr: 'أولوية قصوى (VIP)', color: '#dc2626', orderIndex: 1, createdAt: new Date().toISOString() },
  ];

  // Seed rich tasks across companies
  const baseTasks: any[] = [
    // --- c1-noor-retail (7 tasks) ---
    {
      id: 'task-101',
      companyId: 'c1-noor-retail',
      title: 'Q3 Central Region Inventory Audit',
      description: 'Physical audit of dry foods and non-perishables across 14 central warehouses.',
      statusId: 'ts-5', // completed
      priorityId: 'tp-3', // high
      creatorId: 'u1-super-admin',
      assigneeId: 'u2-admin',
      dueDate: new Date(Date.now() - 5 * 86400000).toISOString(),
      estimatedHours: 36,
      actualHours: 34,
      isArchived: false,
      createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
    {
      id: 'task-102',
      companyId: 'c1-noor-retail',
      title: 'Launch Ramadan Omnichannel Campaign',
      description: 'Deploy print catalogues, digital billboards, and push discount vouchers in mobile app.',
      statusId: 'ts-2', // in_progress
      priorityId: 'tp-4', // urgent / VIP
      creatorId: 'u2-admin',
      assigneeId: 'u3-manager',
      dueDate: new Date(Date.now() + 10 * 86400000).toISOString(),
      estimatedHours: 50,
      actualHours: 28,
      isArchived: false,
      createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'task-103',
      companyId: 'c1-noor-retail',
      title: 'Install Smart Self-Checkout Terminals',
      description: 'Upgrade hardware and test barcode scanners at Olaya flagship hypermarket.',
      statusId: 'ts-1', // todo / pending
      priorityId: 'tp-2', // medium
      creatorId: 'u2-admin',
      assigneeId: 'u2-admin',
      dueDate: new Date(Date.now() + 20 * 86400000).toISOString(),
      estimatedHours: 40,
      isArchived: false,
      createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
    {
      id: 'task-104',
      companyId: 'c1-noor-retail',
      title: 'Dairy Supplier Contract Renegotiation',
      description: 'Annual rebate and pricing adjustment discussion with local dairy producers.',
      statusId: 'ts-4', // blocked / delayed / paused
      priorityId: 'tp-4', // VIP
      creatorId: 'u1-super-admin',
      assigneeId: 'u3-manager',
      dueDate: new Date(Date.now() - 8 * 86400000).toISOString(), // Delayed / overdue
      estimatedHours: 15,
      actualHours: 10,
      isArchived: false,
      createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'task-105',
      companyId: 'c1-noor-retail',
      title: 'Employee Shift Scheduling AI Automation',
      description: 'Review algorithmic shift assignment based on peak shopping footfall.',
      statusId: 'ts-3', // review
      priorityId: 'tp-1', // low
      creatorId: 'u3-manager',
      assigneeId: 'u2-admin',
      dueDate: new Date(Date.now() + 5 * 86400000).toISOString(),
      estimatedHours: 18,
      actualHours: 16,
      isArchived: false,
      createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'task-106',
      companyId: 'c1-noor-retail',
      title: 'Mobile App Payment Gateway Security Patch',
      description: 'Integrate 3D Secure 2.2 protocol and resolve checkout session timeout.',
      statusId: 'ts-5', // completed
      priorityId: 'tp-4', // urgent / VIP
      creatorId: 'u1-super-admin',
      assigneeId: 'u3-manager',
      dueDate: new Date(Date.now() - 12 * 86400000).toISOString(),
      estimatedHours: 24,
      actualHours: 22,
      isArchived: false,
      createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 11 * 86400000).toISOString(),
    },
    {
      id: 'task-107',
      companyId: 'c1-noor-retail',
      title: 'Food Safety & Halal Certification Renewal',
      description: 'Complete inspection with municipal inspectors for fresh meats counter.',
      statusId: 'ts-5', // completed
      priorityId: 'tp-3', // high
      creatorId: 'u2-admin',
      assigneeId: 'u2-admin',
      dueDate: new Date(Date.now() - 25 * 86400000).toISOString(),
      estimatedHours: 16,
      actualHours: 14,
      isArchived: false,
      createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 24 * 86400000).toISOString(),
    },

    // --- c2-apex-logistics (5 tasks) ---
    {
      id: 'task-201',
      companyId: 'c2-apex-logistics',
      title: 'Cold Storage Expansion Feasibility Study',
      description: 'Engineering survey and thermal insulation assessment for Jebel Ali warehouse 3.',
      statusId: 'ts-2', // in_progress
      priorityId: 'tp-4', // urgent / VIP
      creatorId: 'u1-super-admin',
      assigneeId: 'u1-super-admin',
      dueDate: new Date(Date.now() + 14 * 86400000).toISOString(),
      estimatedHours: 60,
      actualHours: 35,
      isArchived: false,
      createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'task-202',
      companyId: 'c2-apex-logistics',
      title: 'Fleet Telematics & GPS Tracker Upgrade',
      description: 'Install OBD-II live telemetry on 85 refrigerated heavy commercial trucks.',
      statusId: 'ts-5', // completed
      priorityId: 'tp-3', // high
      creatorId: 'u1-super-admin',
      assigneeId: 'u1-super-admin',
      dueDate: new Date(Date.now() - 10 * 86400000).toISOString(),
      estimatedHours: 80,
      actualHours: 76,
      isArchived: false,
      createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 9 * 86400000).toISOString(),
    },
    {
      id: 'task-203',
      companyId: 'c2-apex-logistics',
      title: 'Maritime Port Clearance SLA Verification',
      description: 'Analyze average customs dwell time for 20ft containers at King Abdulaziz Port.',
      statusId: 'ts-1', // todo / pending
      priorityId: 'tp-2', // medium
      creatorId: 'u1-super-admin',
      assigneeId: 'u1-super-admin',
      dueDate: new Date(Date.now() + 8 * 86400000).toISOString(),
      estimatedHours: 20,
      isArchived: false,
      createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
    {
      id: 'task-204',
      companyId: 'c2-apex-logistics',
      title: 'Aviation Freight Partner Tariff Negotiation',
      description: 'Secure priority cargo belly-hold rates with Gulf air carriers.',
      statusId: 'ts-4', // delayed / paused
      priorityId: 'tp-4', // urgent / VIP
      creatorId: 'u1-super-admin',
      assigneeId: 'u1-super-admin',
      dueDate: new Date(Date.now() - 6 * 86400000).toISOString(), // Delayed / overdue
      estimatedHours: 30,
      actualHours: 12,
      isArchived: false,
      createdAt: new Date(Date.now() - 16 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
    {
      id: 'task-205',
      companyId: 'c2-apex-logistics',
      title: 'Fire Safety & Hazardous Material Drill',
      description: 'Execute mandated semi-annual evacuation drill with Dubai Civil Defence.',
      statusId: 'ts-5', // completed
      priorityId: 'tp-1', // low
      creatorId: 'u1-super-admin',
      assigneeId: 'u1-super-admin',
      dueDate: new Date(Date.now() - 20 * 86400000).toISOString(),
      estimatedHours: 8,
      actualHours: 8,
      isArchived: false,
      createdAt: new Date(Date.now() - 22 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 19 * 86400000).toISOString(),
    },

    // --- c3-techsphere (6 tasks) ---
    {
      id: 'task-301',
      companyId: 'c3-techsphere',
      title: 'SOC 2 Type II Security Compliance Audit',
      description: 'Review access logs, encryption at rest, and infrastructure segregation controls.',
      statusId: 'ts-2', // in_progress
      priorityId: 'tp-4', // urgent / VIP
      creatorId: 'u1-super-admin',
      assigneeId: 'u2-admin',
      dueDate: new Date(Date.now() + 12 * 86400000).toISOString(),
      estimatedHours: 75,
      actualHours: 45,
      isArchived: false,
      createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'task-302',
      companyId: 'c3-techsphere',
      title: 'Kubernetes Multi-Cluster DR Drill',
      description: 'Simulate regional data center blackout and test RTO/RPO failover under 3 minutes.',
      statusId: 'ts-5', // completed
      priorityId: 'tp-4', // urgent
      creatorId: 'u2-admin',
      assigneeId: 'u2-admin',
      dueDate: new Date(Date.now() - 4 * 86400000).toISOString(),
      estimatedHours: 32,
      actualHours: 30,
      isArchived: false,
      createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
    {
      id: 'task-303',
      companyId: 'c3-techsphere',
      title: 'Enterprise ERP Migration Phase 1',
      description: 'Extract customer schemas, validate UTF-8 Arabic collations, and stage data pipelines.',
      statusId: 'ts-1', // todo / pending
      priorityId: 'tp-3', // high
      creatorId: 'u2-admin',
      assigneeId: 'u2-admin',
      dueDate: new Date(Date.now() + 18 * 86400000).toISOString(),
      estimatedHours: 50,
      isArchived: false,
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'task-304',
      companyId: 'c3-techsphere',
      title: 'AI Document Parsing Engine Integration',
      description: 'Implement optical character recognition and table extraction for incoming supplier invoices.',
      statusId: 'ts-2', // in_progress
      priorityId: 'tp-2', // medium
      creatorId: 'u2-admin',
      assigneeId: 'u2-admin',
      dueDate: new Date(Date.now() + 6 * 86400000).toISOString(),
      estimatedHours: 40,
      actualHours: 24,
      isArchived: false,
      createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'task-305',
      companyId: 'c3-techsphere',
      title: 'Cloudflare Zero-Trust Network Tunnel Setup',
      description: 'Replace legacy OpenVPN with identity-aware Zero Trust network access for remote devs.',
      statusId: 'ts-5', // completed
      priorityId: 'tp-3', // high
      creatorId: 'u1-super-admin',
      assigneeId: 'u2-admin',
      dueDate: new Date(Date.now() - 16 * 86400000).toISOString(),
      estimatedHours: 25,
      actualHours: 21,
      isArchived: false,
      createdAt: new Date(Date.now() - 22 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    },
    {
      id: 'task-306',
      companyId: 'c3-techsphere',
      title: 'Code Security Static Analysis Pipeline Setup',
      description: 'Add SonarQube quality gates to GitHub Actions workflow.',
      statusId: 'ts-5', // completed
      priorityId: 'tp-1', // low
      creatorId: 'u2-admin',
      assigneeId: 'u2-admin',
      dueDate: new Date(Date.now() - 28 * 86400000).toISOString(),
      estimatedHours: 12,
      actualHours: 10,
      isArchived: false,
      createdAt: new Date(Date.now() - 32 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 27 * 86400000).toISOString(),
    },

    // --- c4-horizon-media (4 tasks) ---
    {
      id: 'task-401',
      companyId: 'c4-horizon-media',
      title: 'Founding Day 2026 Creative Pitch Deck',
      description: 'Develop video storyboards, typography styling, and 3D social clips for national sponsors.',
      statusId: 'ts-2', // in_progress
      priorityId: 'tp-4', // urgent / VIP
      creatorId: 'u1-super-admin',
      assigneeId: 'u3-manager',
      dueDate: new Date(Date.now() + 7 * 86400000).toISOString(),
      estimatedHours: 35,
      actualHours: 22,
      isArchived: false,
      createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'task-402',
      companyId: 'c4-horizon-media',
      title: 'Broadcast Studio Camera Kit Procurement',
      description: 'Compare Red Digital Cinema vs Sony FX9 packages for Khobar studio expansion.',
      statusId: 'ts-4', // blocked / delayed / paused
      priorityId: 'tp-3', // high
      creatorId: 'u3-manager',
      assigneeId: 'u3-manager',
      dueDate: new Date(Date.now() - 10 * 86400000).toISOString(), // Delayed / overdue
      estimatedHours: 20,
      actualHours: 8,
      isArchived: false,
      createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
    {
      id: 'task-403',
      companyId: 'c4-horizon-media',
      title: 'Digital Influencer Endorsement Contracts',
      description: 'Formalize FTC & General Authority of Media regulatory compliance contracts.',
      statusId: 'ts-5', // completed
      priorityId: 'tp-3', // high
      creatorId: 'u3-manager',
      assigneeId: 'u3-manager',
      dueDate: new Date(Date.now() - 14 * 86400000).toISOString(),
      estimatedHours: 22,
      actualHours: 20,
      isArchived: false,
      createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 13 * 86400000).toISOString(),
    },
    {
      id: 'task-404',
      companyId: 'c4-horizon-media',
      title: 'Agency Website Overhaul & Showreel Update',
      description: 'Render WebGL interactive reel and publish case studies for 2025 awards.',
      statusId: 'ts-3', // review
      priorityId: 'tp-2', // medium
      creatorId: 'u3-manager',
      assigneeId: 'u3-manager',
      dueDate: new Date(Date.now() + 4 * 86400000).toISOString(),
      estimatedHours: 28,
      actualHours: 26,
      isArchived: false,
      createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },

    // --- c5-gulf-capital (4 tasks) ---
    {
      id: 'task-501',
      companyId: 'c5-gulf-capital',
      title: 'Sharq Commercial Tower Groundbreaking Event',
      description: 'Coordinate VIP protocol, media coverage, and contractor ribbon-cutting in Kuwait City.',
      statusId: 'ts-5', // completed
      priorityId: 'tp-4', // urgent / VIP
      creatorId: 'u1-super-admin',
      assigneeId: 'u1-super-admin',
      dueDate: new Date(Date.now() - 8 * 86400000).toISOString(),
      estimatedHours: 40,
      actualHours: 38,
      isArchived: false,
      createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    },
    {
      id: 'task-502',
      companyId: 'c5-gulf-capital',
      title: 'Kuwait Municipality Environmental Impact Assessment',
      description: 'Finalize traffic density and carbon offset filings with urban planning ministry.',
      statusId: 'ts-2', // in_progress
      priorityId: 'tp-3', // high
      creatorId: 'u1-super-admin',
      assigneeId: 'u1-super-admin',
      dueDate: new Date(Date.now() + 15 * 86400000).toISOString(),
      estimatedHours: 45,
      actualHours: 20,
      isArchived: false,
      createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'task-503',
      companyId: 'c5-gulf-capital',
      title: 'Q1 Real Estate Asset Portfolio Appraisal',
      description: 'Third-party RICS registered valuer appraisal of commercial residential blocks.',
      statusId: 'ts-5', // completed
      priorityId: 'tp-2', // medium
      creatorId: 'u1-super-admin',
      assigneeId: 'u1-super-admin',
      dueDate: new Date(Date.now() - 15 * 86400000).toISOString(),
      estimatedHours: 30,
      actualHours: 28,
      isArchived: false,
      createdAt: new Date(Date.now() - 24 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    },
    {
      id: 'task-504',
      companyId: 'c5-gulf-capital',
      title: 'Prime Anchor Tenant Lease Finalization',
      description: 'Legal review of 10-year triple net lease for banking institution headquarters.',
      statusId: 'ts-1', // todo / pending
      priorityId: 'tp-4', // urgent / VIP
      creatorId: 'u1-super-admin',
      assigneeId: 'u1-super-admin',
      dueDate: new Date(Date.now() + 25 * 86400000).toISOString(),
      estimatedHours: 35,
      isArchived: false,
      createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    },

    // --- c6-al-moneash (Al-Moneash AMC-8432, Iraq) ---
    {
      id: 'task-601',
      companyId: 'c6-al-moneash',
      title: 'خطة التوزيع للمحافظات الوسطى والجنوبية (بغداد، البصرة، النجف)',
      description: 'إعادة جدولة مسارات شاحنات التوزيع وتحديث مراكز الشحن والتفريغ الرئيسية.',
      statusId: 'ts-2', // in_progress
      priorityId: 'tp-4', // urgent / VIP
      creatorId: 'u1-super-admin',
      assigneeId: 'u1-super-admin',
      dueDate: new Date(Date.now() + 8 * 86400000).toISOString(),
      estimatedHours: 45,
      actualHours: 20,
      isArchived: false,
      createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      id: 'task-602',
      companyId: 'c6-al-moneash',
      title: 'تسوية الحسابات المالية بالدينار العراقي والدولار للربع السنوي',
      description: 'مراجعة قيود المبيعات والتحصيلات بالدينار العراقي IQD والدولار الأمريكي USD واعتماد كشوفات البنوك.',
      statusId: 'ts-5', // completed
      priorityId: 'tp-3', // high
      creatorId: 'u1-super-admin',
      assigneeId: 'u2-admin',
      dueDate: new Date(Date.now() - 2 * 86400000).toISOString(),
      estimatedHours: 30,
      actualHours: 29,
      isArchived: false,
      createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'task-603',
      companyId: 'c6-al-moneash',
      title: 'تجديد عقود الوكالات الحصرية وتراخيص الاستيراد',
      description: 'استكمال إجراءات وزارة التجارة والهيئة العامة للكمارك والتراخيص الرسمية.',
      statusId: 'ts-1', // pending
      priorityId: 'tp-3', // high
      creatorId: 'u2-admin',
      assigneeId: 'u3-manager',
      dueDate: new Date(Date.now() + 18 * 86400000).toISOString(),
      estimatedHours: 40,
      isArchived: false,
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'task-604',
      companyId: 'c6-al-moneash',
      title: 'تركيب أنظمة التتبع GPS ومراقبة المخازن في بغداد',
      description: 'تثبيت الكاميرات الحرارية وأجهزة التتبع على الأسطول الرئيسي لمستودعات الكرخ والرصافة.',
      statusId: 'ts-3', // review
      priorityId: 'tp-2', // medium
      creatorId: 'u1-super-admin',
      assigneeId: 'u3-manager',
      dueDate: new Date(Date.now() + 5 * 86400000).toISOString(),
      estimatedHours: 25,
      actualHours: 22,
      isArchived: false,
      createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
  ];

  // Seed Company Files repository
  const companyFiles: CompanyFile[] = [
    {
      id: 'file-101',
      companyId: 'c1-noor-retail',
      name: 'Commercial_Registration_CR1010998822.pdf',
      category: 'registration',
      fileSize: 2450000,
      mimeType: 'application/pdf',
      fileUrl: '#',
      uploaderId: 'u1-super-admin',
      uploaderName: 'Tariq Al-Mansoor',
      createdAt: new Date('2026-01-12').toISOString(),
    },
    {
      id: 'file-102',
      companyId: 'c1-noor-retail',
      name: 'ZATCA_Tax_Compliance_Clearance_2025.pdf',
      category: 'financial',
      fileSize: 1840000,
      mimeType: 'application/pdf',
      fileUrl: '#',
      uploaderId: 'u2-admin',
      uploaderName: 'Sara Al-Otaibi',
      createdAt: new Date('2026-01-20').toISOString(),
    },
    {
      id: 'file-103',
      companyId: 'c1-noor-retail',
      name: 'Master_Vendor_Supply_Agreement_v4.docx',
      category: 'contract',
      fileSize: 520000,
      mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      fileUrl: '#',
      uploaderId: 'u3-manager',
      uploaderName: 'Faisal Al-Ghamdi',
      createdAt: new Date('2026-02-05').toISOString(),
    },
    {
      id: 'file-104',
      companyId: 'c1-noor-retail',
      name: 'Occupational_Health_Safety_Code_2026.pdf',
      category: 'policy',
      fileSize: 3100000,
      mimeType: 'application/pdf',
      fileUrl: '#',
      uploaderId: 'u2-admin',
      uploaderName: 'Sara Al-Otaibi',
      createdAt: new Date('2026-02-14').toISOString(),
    },
    {
      id: 'file-201',
      companyId: 'c2-apex-logistics',
      name: 'UAE_Customs_Authority_Broker_Permit.pdf',
      category: 'registration',
      fileSize: 1980000,
      mimeType: 'application/pdf',
      fileUrl: '#',
      uploaderId: 'u1-super-admin',
      uploaderName: 'Tariq Al-Mansoor',
      createdAt: new Date('2026-01-18').toISOString(),
    },
    {
      id: 'file-202',
      companyId: 'c2-apex-logistics',
      name: 'Marine_Cargo_All_Risks_Policy_2026.pdf',
      category: 'contract',
      fileSize: 4200000,
      mimeType: 'application/pdf',
      fileUrl: '#',
      uploaderId: 'u1-super-admin',
      uploaderName: 'Tariq Al-Mansoor',
      createdAt: new Date('2026-01-25').toISOString(),
    },
    {
      id: 'file-301',
      companyId: 'c3-techsphere',
      name: 'ISO_27001_Information_Security_Cert.pdf',
      category: 'policy',
      fileSize: 2890000,
      mimeType: 'application/pdf',
      fileUrl: '#',
      uploaderId: 'u2-admin',
      uploaderName: 'Sara Al-Otaibi',
      createdAt: new Date('2026-02-02').toISOString(),
    },
    {
      id: 'file-302',
      companyId: 'c3-techsphere',
      name: 'Enterprise_SaaS_Service_Level_Agreement.pdf',
      category: 'contract',
      fileSize: 850000,
      mimeType: 'application/pdf',
      fileUrl: '#',
      uploaderId: 'u2-admin',
      uploaderName: 'Sara Al-Otaibi',
      createdAt: new Date('2026-02-10').toISOString(),
    },
    {
      id: 'file-401',
      companyId: 'c4-horizon-media',
      name: 'GCAM_Media_Broadcasting_License_2026.pdf',
      category: 'registration',
      fileSize: 1720000,
      mimeType: 'application/pdf',
      fileUrl: '#',
      uploaderId: 'u3-manager',
      uploaderName: 'Faisal Al-Ghamdi',
      createdAt: new Date('2026-02-18').toISOString(),
    },
    {
      id: 'file-501',
      companyId: 'c5-gulf-capital',
      name: 'Capital_Markets_Authority_Prospectus.pdf',
      category: 'financial',
      fileSize: 5800000,
      mimeType: 'application/pdf',
      fileUrl: '#',
      uploaderId: 'u1-super-admin',
      uploaderName: 'Tariq Al-Mansoor',
      createdAt: new Date('2026-03-02').toISOString(),
    },
  ];

  const customFields: CustomField[] = [
    {
      id: 'cf-budget-code',
      nameAr: 'رمز الميزانية التشغيلية',
      nameEn: 'Budget Account Code',
      fieldKey: 'budget_code',
      type: 'text',
      required: true,
      defaultValue: 'OPEX-2026',
      visibility: 'all',
      companyIds: [],
      roleSlugs: [],
      sortOrder: 1,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'cf-exec-summary',
      nameAr: 'المبررات التنفيذية والجدوى',
      nameEn: 'Executive Justification',
      fieldKey: 'executive_justification',
      type: 'long_text',
      required: false,
      defaultValue: '',
      visibility: 'all',
      companyIds: [],
      roleSlugs: [],
      sortOrder: 2,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'cf-estimated-cost',
      nameAr: 'التكلفة المالية المقدرة',
      nameEn: 'Estimated Cost',
      fieldKey: 'estimated_cost',
      type: 'number',
      required: false,
      defaultValue: 0,
      visibility: 'all',
      companyIds: [],
      roleSlugs: [],
      sortOrder: 3,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'cf-inspection-date',
      nameAr: 'تاريخ الفحص الميداني',
      nameEn: 'Field Inspection Date',
      fieldKey: 'inspection_date',
      type: 'date',
      required: false,
      visibility: 'all',
      companyIds: [],
      roleSlugs: [],
      sortOrder: 4,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'cf-committee-meeting',
      nameAr: 'موعد اجتماع اللجنة الفنية',
      nameEn: 'Committee Meeting Time',
      fieldKey: 'committee_meeting_time',
      type: 'date_time',
      required: false,
      visibility: 'all',
      companyIds: [],
      roleSlugs: [],
      sortOrder: 5,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'cf-branch-location',
      nameAr: 'الفرع المستهدف',
      nameEn: 'Target Branch',
      fieldKey: 'target_branch',
      type: 'dropdown',
      options: ['الرياض - المقر الرئيسي', 'جدة - الكورنيش', 'الدمام - بوابة الخليج', 'الخبر - مول الراشد', 'دبي - جبل علي', 'الكويت - برج الشرق'],
      required: true,
      defaultValue: 'الرياض - المقر الرئيسي',
      visibility: 'all',
      companyIds: [],
      roleSlugs: [],
      sortOrder: 6,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'cf-affected-depts',
      nameAr: 'الإدارات المعنية بالتنفيذ',
      nameEn: 'Involved Departments',
      fieldKey: 'involved_depts',
      type: 'multi_select',
      options: ['إدارة العمليات', 'الإدارة المالية', 'تقنية المعلومات', 'الشؤون القانونية', 'سلاسل الإمداد', 'الموارد البشرية'],
      required: false,
      defaultValue: ['إدارة العمليات'],
      visibility: 'all',
      companyIds: [],
      roleSlugs: [],
      sortOrder: 7,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'cf-board-approval',
      nameAr: 'يتطلب موافقة مجلس الإدارة',
      nameEn: 'Requires Board Approval',
      fieldKey: 'requires_board_approval',
      type: 'checkbox',
      required: false,
      defaultValue: false,
      visibility: 'all',
      companyIds: [],
      roleSlugs: [],
      sortOrder: 8,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'cf-risk-level',
      nameAr: 'تصنيف مستوى المخاطر الرقابية',
      nameEn: 'Risk Classification',
      fieldKey: 'risk_classification',
      type: 'radio',
      options: ['منخفضة (Low)', 'متوسطة (Medium)', 'حرجة (Critical)'],
      required: true,
      defaultValue: 'متوسطة (Medium)',
      visibility: 'all',
      companyIds: [],
      roleSlugs: [],
      sortOrder: 9,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'cf-certified-supervisor',
      nameAr: 'المشرف الفني المعتمد',
      nameEn: 'Assigned Supervisor',
      fieldKey: 'assigned_supervisor',
      type: 'user_selector',
      required: false,
      defaultValue: 'u2-admin',
      visibility: 'all',
      companyIds: [],
      roleSlugs: [],
      sortOrder: 10,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'cf-partner-entity',
      nameAr: 'الجهة أو الشركة الشقيقة الشريكة',
      nameEn: 'Partner Sister Company',
      fieldKey: 'partner_company',
      type: 'company_selector',
      required: false,
      defaultValue: 'c2-apex-logistics',
      visibility: 'all',
      companyIds: [],
      roleSlugs: [],
      sortOrder: 11,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'cf-approval-attachment',
      nameAr: 'محضر الاعتماد الموقّع',
      nameEn: 'Signed Approval Memo',
      fieldKey: 'signed_approval_memo',
      type: 'file_upload',
      required: false,
      defaultValue: '',
      visibility: 'all',
      companyIds: [],
      roleSlugs: [],
      sortOrder: 12,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  // Enrich tasks with complete phase 4 attributes, assignments, reasons, notes, attachments, and timeline
  const enrichedTasks: Task[] = baseTasks.map((t, idx) => {
    let prioritySlug: TaskPrioritySlug = 'medium';
    if (t.priorityId === 'tp-4') prioritySlug = 'vip';
    else if (t.priorityId === 'tp-3') prioritySlug = 'high';
    else if (t.priorityId === 'tp-1') prioritySlug = 'low';

    let statusSlug: TaskStatusSlug = 'pending';
    if (t.statusId === 'ts-5') statusSlug = 'completed';
    else if (t.statusId === 'ts-4') statusSlug = idx % 2 === 0 ? 'delayed' : 'paused';
    else if (t.statusId === 'ts-2' || t.statusId === 'ts-3') statusSlug = 'in_progress';
    else if (idx === 15) statusSlug = 'cancelled';

    const codeNum = String(idx).padStart(4, '0');
    const taskCode = `TSK-${codeNum}`;

    const startDate = new Date(new Date(t.createdAt).getTime() + 86400000).toISOString();
    const isDone = statusSlug === 'completed';
    const completionDate = isDone ? t.updatedAt : undefined;

    let statusReason: string | undefined = undefined;
    if (statusSlug === 'delayed') {
      statusReason = 'بانتظار موافقة واعتماد لجنة المشتريات على عروض الأسعار التنافسية / Waiting for procurement committee price sign-off';
    } else if (statusSlug === 'paused') {
      statusReason = 'توقف مؤقت لمراجعة معايير السلامة المهنية ومطابقة لوائح هيئة المواصفات / Paused pending safety review';
    }

    const assignedToId = t.assigneeId || (idx % 2 === 0 ? 'u2-admin' : 'u3-manager');
    const responsiblePersonId = 'u1-super-admin';
    const recipientId = assignedToId === 'u3-manager' ? 'u2-admin' : 'u3-manager';

    const timeline: TaskTimelineEvent[] = [
      {
        id: `tl-${t.id}-1`,
        taskId: t.id,
        type: 'created',
        userId: t.creatorId,
        userName: t.creatorId === 'u1-super-admin' ? 'Tariq Al-Mansoor' : 'Sara Al-Otaibi',
        date: t.createdAt.split('T')[0],
        time: t.createdAt.split('T')[1].substring(0, 5),
        details: 'Initial task creation with baseline requirements',
        createdAt: t.createdAt,
      },
      {
        id: `tl-${t.id}-2`,
        taskId: t.id,
        type: 'assigned',
        userId: t.creatorId,
        userName: t.creatorId === 'u1-super-admin' ? 'Tariq Al-Mansoor' : 'Sara Al-Otaibi',
        date: t.createdAt.split('T')[0],
        time: t.createdAt.split('T')[1].substring(0, 5),
        oldValue: null,
        newValue: assignedToId,
        details: 'Assigned task to operational specialist',
        createdAt: t.createdAt,
      },
    ];

    if (statusSlug !== 'pending') {
      timeline.push({
        id: `tl-${t.id}-3`,
        taskId: t.id,
        type: statusSlug === 'completed' ? 'completed' : 'status_changed',
        userId: assignedToId,
        userName: assignedToId === 'u3-manager' ? 'Faisal Al-Ghamdi' : 'Sara Al-Otaibi',
        date: t.updatedAt.split('T')[0],
        time: t.updatedAt.split('T')[1].substring(0, 5),
        oldValue: 'pending',
        newValue: statusSlug,
        reason: statusReason,
        details: `Task status updated to ${statusSlug.toUpperCase()}`,
        createdAt: t.updatedAt,
      });
    }

    const notes: TaskNote[] = [
      {
        id: `note-${t.id}-1`,
        taskId: t.id,
        userId: t.creatorId,
        userName: t.creatorId === 'u1-super-admin' ? 'Tariq Al-Mansoor' : 'Sara Al-Otaibi',
        content: 'يرجى الالتزام الصارم بالجدول الزمني المعتمد وتحديث سجل الملاحظات أولاً بأول لضمان الامتثال المؤسسي.',
        isInternalOnly: false,
        createdAt: t.createdAt,
        updatedAt: t.createdAt,
      },
      {
        id: `note-${t.id}-2`,
        taskId: t.id,
        userId: assignedToId,
        userName: assignedToId === 'u3-manager' ? 'Faisal Al-Ghamdi' : 'Sara Al-Otaibi',
        content: 'تم البدء في التنسيق الميداني مع فريق العمل واستلام كافة المخرجات والمستندات الأولية.',
        isInternalOnly: true,
        createdAt: t.updatedAt,
        updatedAt: t.updatedAt,
      },
    ];

    const attachments: TaskAttachment[] = [
      {
        id: `att-${t.id}-1`,
        taskId: t.id,
        uploaderId: t.creatorId,
        uploaderName: t.creatorId === 'u1-super-admin' ? 'Tariq Al-Mansoor' : 'Sara Al-Otaibi',
        fileName: `Project_Scope_Spec_${taskCode}.pdf`,
        fileSize: 450000 + (idx * 35000),
        mimeType: 'application/pdf',
        fileUrl: '#',
        createdAt: t.createdAt,
      },
      {
        id: `att-${t.id}-2`,
        taskId: t.id,
        uploaderId: assignedToId,
        uploaderName: assignedToId === 'u3-manager' ? 'Faisal Al-Ghamdi' : 'Sara Al-Otaibi',
        fileName: `Implementation_Checklist_v1.docx`,
        fileSize: 180000 + (idx * 20000),
        mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        fileUrl: '#',
        createdAt: t.updatedAt,
      },
    ];

    return {
      ...t,
      taskCode,
      priority: prioritySlug,
      status: statusSlug,
      statusReason,
      assignedToId,
      responsiblePersonId,
      recipientId,
      startDate,
      completionDate,
      customFields: {
        'cf-budget-code': `BUDGET-2026-${100 + idx}`,
        'cf-branch-location': idx % 2 === 0 ? 'الرياض - المقر الرئيسي' : 'جدة - الكورنيش',
        'cf-estimated-cost': 20000 + (idx * 7500),
        'cf-board-approval': prioritySlug === 'vip',
        'cf-risk-level': prioritySlug === 'vip' ? 'حرجة (Critical)' : 'متوسطة (Medium)',
        'cf-affected-depts': ['إدارة العمليات', 'الإدارة المالية'],
        'cf-partner-entity': 'c2-apex-logistics',
      },
      notes,
      attachments,
      timeline,
    };
  });

  const now = Date.now();
  const getIso = (minutesAgo: number) => new Date(now - minutesAgo * 60000).toISOString();
  const getDate = (minutesAgo: number) => getIso(minutesAgo).split('T')[0];
  const getTime = (minutesAgo: number) => getIso(minutesAgo).split('T')[1].substring(0, 8);

  const auditLogs = [
    {
      id: 'log-1',
      userId: 'u1-super-admin',
      userName: 'خالد المنصور (Super Admin)',
      userEmail: 'superadmin@holding.com',
      companyId: null,
      companyName: 'Holding Group',
      action: 'LOGIN',
      entity: 'AUTH',
      entityId: 'u1-super-admin',
      oldValue: null,
      newValue: 'Session started successfully with 2FA verification',
      date: getDate(180),
      time: getTime(180),
      ipAddress: '192.168.1.102',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
      status: 'SUCCESS',
      details: { authMethod: 'password_and_token', scope: 'GLOBAL' },
      createdAt: getIso(180),
      resource: 'AUTH',
      resourceId: 'u1-super-admin',
    },
    {
      id: 'log-2',
      userId: 'u1-super-admin',
      userName: 'خالد المنصور (Super Admin)',
      userEmail: 'superadmin@holding.com',
      companyId: 'c1-noor-retail',
      companyName: 'Al-Noor Retail Group',
      action: 'CREATE',
      entity: 'COMPANIES',
      entityId: 'RET-NOOR',
      oldValue: null,
      newValue: 'Al-Noor Retail Group (مجموعة النور للتجزئة)',
      date: getDate(160),
      time: getTime(160),
      ipAddress: '192.168.1.102',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
      status: 'SUCCESS',
      details: { code: 'RET-NOOR', currency: 'IQD', country: 'IQ' },
      createdAt: getIso(160),
      resource: 'COMPANIES',
      resourceId: 'c1-noor-retail',
    },
    {
      id: 'log-3',
      userId: 'u1-super-admin',
      userName: 'خالد المنصور (Super Admin)',
      userEmail: 'superadmin@holding.com',
      companyId: null,
      companyName: 'Holding Group',
      action: 'PERMISSION_CHANGE',
      entity: 'ROLES',
      entityId: 'admin',
      oldValue: '4 permissions granted',
      newValue: '9 permissions granted (Enabled Reports & Custom Fields)',
      date: getDate(140),
      time: getTime(140),
      ipAddress: '192.168.1.102',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
      status: 'SUCCESS',
      details: { roleSlug: 'admin', updatedBy: 'u1-super-admin' },
      createdAt: getIso(140),
      resource: 'ROLES',
      resourceId: 'role-admin',
    },
    {
      id: 'log-4',
      userId: 'u2-admin',
      userName: 'سارة الشمري (Admin)',
      userEmail: 'admin@alnoor-retail.sa',
      companyId: 'c1-noor-retail',
      companyName: 'Al-Noor Retail Group',
      action: 'CREATE',
      entity: 'TASKS',
      entityId: 'RET-2026-001',
      oldValue: null,
      newValue: 'ترقية البنية التحتية لمنظومة نقاط البيع (POS)',
      date: getDate(120),
      time: getTime(120),
      ipAddress: '10.0.4.15',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
      status: 'SUCCESS',
      details: { priority: 'vip', status: 'pending', assignedTo: 'u3-manager' },
      createdAt: getIso(120),
      resource: 'TASKS',
      resourceId: 'RET-2026-001',
    },
    {
      id: 'log-5',
      userId: 'u3-manager',
      userName: 'فيصل القحطاني (Manager)',
      userEmail: 'manager@alnoor-retail.sa',
      companyId: 'c1-noor-retail',
      companyName: 'Al-Noor Retail Group',
      action: 'STATUS_CHANGE',
      entity: 'TASKS',
      entityId: 'RET-2026-001',
      oldValue: 'pending (قيد الانتظار)',
      newValue: 'in_progress (قيد التنفيذ)',
      date: getDate(100),
      time: getTime(100),
      ipAddress: '10.0.4.88',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
      status: 'SUCCESS',
      details: { reason: 'بدء مرحلة الفحص الميداني للسيرفرات' },
      createdAt: getIso(100),
      resource: 'TASKS',
      resourceId: 'RET-2026-001',
    },
    {
      id: 'log-6',
      userId: 'u3-manager',
      userName: 'فيصل القحطاني (Manager)',
      userEmail: 'manager@alnoor-retail.sa',
      companyId: 'c1-noor-retail',
      companyName: 'Al-Noor Retail Group',
      action: 'FILE_UPLOAD',
      entity: 'ATTACHMENTS',
      entityId: 'att-seed-1',
      oldValue: null,
      newValue: 'Technical_Specification_POS_v3.pdf (2,450 KB) [Private / سري]',
      date: getDate(85),
      time: getTime(85),
      ipAddress: '10.0.4.88',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
      status: 'SUCCESS',
      details: { fileName: 'Technical_Specification_POS_v3.pdf', fileSize: 2508800, isPrivate: true },
      createdAt: getIso(85),
      resource: 'ATTACHMENTS',
      resourceId: 'att-seed-1',
    },
    {
      id: 'log-7',
      userId: 'u3-manager',
      userName: 'فيصل القحطاني (Manager)',
      userEmail: 'manager@alnoor-retail.sa',
      companyId: 'c1-noor-retail',
      companyName: 'Al-Noor Retail Group',
      action: 'STATUS_CHANGE',
      entity: 'TASKS',
      entityId: 'RET-2026-003',
      oldValue: 'in_progress (قيد التنفيذ)',
      newValue: 'delayed (متأخرة) - تأخر توريد أجهزة التوزيع من المورد',
      date: getDate(65),
      time: getTime(65),
      ipAddress: '10.0.4.88',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
      status: 'WARNING',
      details: { reason: 'تأخر توريد أجهزة التوزيع من المورد الرئيسي' },
      createdAt: getIso(65),
      resource: 'TASKS',
      resourceId: 'RET-2026-003',
    },
    {
      id: 'log-8',
      userId: 'u2-admin',
      userName: 'سارة الشمري (Admin)',
      userEmail: 'admin@alnoor-retail.sa',
      companyId: 'c1-noor-retail',
      companyName: 'Al-Noor Retail Group',
      action: 'UPDATE',
      entity: 'TASKS',
      entityId: 'RET-2026-001',
      oldValue: 'DueDate: 2026-04-10, EstimatedHours: 35',
      newValue: 'DueDate: 2026-04-18, EstimatedHours: 48',
      date: getDate(45),
      time: getTime(45),
      ipAddress: '10.0.4.15',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
      status: 'SUCCESS',
      details: { updatedFields: ['dueDate', 'estimatedHours'] },
      createdAt: getIso(45),
      resource: 'TASKS',
      resourceId: 'RET-2026-001',
    },
    {
      id: 'log-9',
      userId: 'u1-super-admin',
      userName: 'خالد المنصور (Super Admin)',
      userEmail: 'superadmin@holding.com',
      companyId: 'c2-apex-logistics',
      companyName: 'Apex Global Logistics',
      action: 'COMPANY_CHANGE',
      entity: 'COMPANIES',
      entityId: 'LOG-APEX',
      oldValue: 'Currency: USD, ContactPhone: +966 12 555 0199',
      newValue: 'Currency: IQD, ContactPhone: +964 77 123 4567',
      date: getDate(30),
      time: getTime(30),
      ipAddress: '192.168.1.102',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
      status: 'SUCCESS',
      details: { updatedFields: ['currency', 'contactPhone'] },
      createdAt: getIso(30),
      resource: 'COMPANIES',
      resourceId: 'c2-apex-logistics',
    },
    {
      id: 'log-10',
      userId: 'u1-super-admin',
      userName: 'خالد المنصور (Super Admin)',
      userEmail: 'superadmin@holding.com',
      companyId: null,
      companyName: 'Holding Group',
      action: 'USER_CHANGE',
      entity: 'USERS',
      entityId: 'u4-lead',
      oldValue: 'Phone: +966 50 111 2233',
      newValue: 'Phone: +966 55 999 8877, AssignedCompanies: Retail + Logistics',
      date: getDate(20),
      time: getTime(20),
      ipAddress: '192.168.1.102',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
      status: 'SUCCESS',
      details: { targetEmail: 'lead@alnoor-retail.sa' },
      createdAt: getIso(20),
      resource: 'USERS',
      resourceId: 'u4-lead',
    },
    {
      id: 'log-11',
      userId: 'u2-admin',
      userName: 'سارة الشمري (Admin)',
      userEmail: 'admin@alnoor-retail.sa',
      companyId: 'c1-noor-retail',
      companyName: 'Al-Noor Retail Group',
      action: 'ARCHIVE',
      entity: 'TASKS',
      entityId: 'RET-2025-089',
      oldValue: 'Active Task: جرد الأصول الثابتة السنوي 2025',
      newValue: 'Archived / مؤرشفة',
      date: getDate(15),
      time: getTime(15),
      ipAddress: '10.0.4.15',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
      status: 'SUCCESS',
      details: { isArchived: true },
      createdAt: getIso(15),
      resource: 'TASKS',
      resourceId: 'RET-2025-089',
    },
    {
      id: 'log-12',
      userId: 'u1-super-admin',
      userName: 'خالد المنصور (Super Admin)',
      userEmail: 'superadmin@holding.com',
      companyId: 'c3-techsphere',
      companyName: 'TechSphere Cloud Solutions',
      action: 'DELETE',
      entity: 'ATTACHMENTS',
      entityId: 'att-obsolete-99',
      oldValue: 'Draft_Proposal_Deprecated.docx',
      newValue: null,
      date: getDate(10),
      time: getTime(10),
      ipAddress: '192.168.1.102',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
      status: 'SUCCESS',
      details: { fileName: 'Draft_Proposal_Deprecated.docx' },
      createdAt: getIso(10),
      resource: 'ATTACHMENTS',
      resourceId: 'att-obsolete-99',
    },
    {
      id: 'log-13',
      userId: 'u3-manager',
      userName: 'فيصل القحطاني (Manager)',
      userEmail: 'manager@alnoor-retail.sa',
      companyId: 'c1-noor-retail',
      companyName: 'Al-Noor Retail Group',
      action: 'LOGOUT',
      entity: 'AUTH',
      entityId: 'u3-manager',
      oldValue: 'Active Session',
      newValue: 'Session Closed',
      date: getDate(5),
      time: getTime(5),
      ipAddress: '10.0.4.88',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
      status: 'SUCCESS',
      details: { sessionDurationMinutes: 95 },
      createdAt: getIso(5),
      resource: 'AUTH',
      resourceId: 'u3-manager',
    },
  ];

  // Seed rich notifications covering ALL 8 required types
  const notifications = [
    {
      id: 'notif-1',
      userId: 'u1-super-admin',
      companyId: 'c1-noor-retail',
      taskId: 'task-101',
      taskCode: 'TSK-0000',
      type: 'new_task',
      titleEn: 'New Task Created',
      titleAr: 'تم إنشاء مهمة جديدة',
      messageEn: 'Task TSK-0000 "Q3 Central Region Inventory Audit" was created in Al-Noor Retail.',
      messageAr: 'تم إنشاء المهمة TSK-0000 "التدقيق الميداني للمخازن المركزية" في مجموعة النور.',
      isRead: false,
      actionUrl: '/tasks?taskId=task-101',
      createdAt: getIso(120),
    },
    {
      id: 'notif-2',
      userId: 'u1-super-admin',
      companyId: 'c1-noor-retail',
      taskId: 'task-101',
      taskCode: 'TSK-0000',
      type: 'task_assigned',
      titleEn: 'Task Assigned to You',
      titleAr: 'تم تعيينك مديراً لمهمة جديدة',
      messageEn: 'You were assigned as supervisor for task TSK-0000.',
      messageAr: 'تم تعيينك كمشرف ومسؤول رئيسي عن المهمة TSK-0000.',
      isRead: false,
      actionUrl: '/tasks?taskId=task-101',
      createdAt: getIso(110),
    },
    {
      id: 'notif-3',
      userId: 'u1-super-admin',
      companyId: 'c1-noor-retail',
      taskId: 'task-102',
      taskCode: 'TSK-0001',
      type: 'status_changed',
      titleEn: 'Status Changed to In Progress',
      titleAr: 'تغيرت حالة المهمة إلى قيد التنفيذ',
      messageEn: 'Task TSK-0001 transitioned from Pending to In Progress by Sara Al-Otaibi.',
      messageAr: 'تم تحديث حالة المهمة TSK-0001 من قيد الانتظار إلى قيد التنفيذ بواسطة سارة العتيبي.',
      isRead: false,
      actionUrl: '/tasks?taskId=task-102',
      createdAt: getIso(90),
    },
    {
      id: 'notif-4',
      userId: 'u1-super-admin',
      companyId: 'c1-noor-retail',
      taskId: 'task-103',
      taskCode: 'TSK-0002',
      type: 'task_delayed',
      titleEn: 'Alert: Task Delayed',
      titleAr: 'تنبيه: تم تأخير المهمة',
      messageEn: 'Task TSK-0002 was marked Delayed: Hardware delivery pending.',
      messageAr: 'تم تعيين المهمة TSK-0002 كمتأخرة: تأخر توريد أجهزة التوزيع من المورد الرئيسي.',
      isRead: false,
      actionUrl: '/tasks?taskId=task-103',
      createdAt: getIso(60),
    },
    {
      id: 'notif-5',
      userId: 'u1-super-admin',
      companyId: 'c1-noor-retail',
      taskId: 'task-101',
      taskCode: 'TSK-0000',
      type: 'task_completed',
      titleEn: 'Task Successfully Completed',
      titleAr: 'اكتملت المهمة بنجاح',
      messageEn: 'Task TSK-0000 "Q3 Central Region Inventory Audit" has been completed.',
      messageAr: 'تم إنجاز المهمة TSK-0000 "التدقيق الميداني للمخازن المركزية" بالكامل.',
      isRead: true,
      actionUrl: '/tasks?taskId=task-101',
      createdAt: getIso(45),
    },
    {
      id: 'notif-6',
      userId: 'u1-super-admin',
      companyId: 'c1-noor-retail',
      taskId: 'task-101',
      taskCode: 'TSK-0000',
      type: 'new_note',
      titleEn: 'New Note Added to Task',
      titleAr: 'ملاحظة جديدة على المهمة',
      messageEn: 'Sara Al-Otaibi posted a confidential note regarding inventory schedules.',
      messageAr: 'أضافت سارة العتيبي توجيهاً داخلياً بخصوص الجداول الزمنية لتسليم المخزون.',
      isRead: true,
      actionUrl: '/tasks?taskId=task-101',
      createdAt: getIso(35),
    },
    {
      id: 'notif-7',
      userId: 'u1-super-admin',
      companyId: 'c1-noor-retail',
      taskId: 'task-102',
      taskCode: 'TSK-0001',
      type: 'task_updated',
      titleEn: 'Task Details Updated',
      titleAr: 'تم تعديل تفاصيل المهمة',
      messageEn: 'Due date extended and estimated hours updated.',
      messageAr: 'تم تمديد تاريخ الاستحقاق وتعديل الساعات المقدرة للمهمة.',
      isRead: true,
      actionUrl: '/tasks?taskId=task-102',
      createdAt: getIso(25),
    },
    {
      id: 'notif-8',
      userId: 'u1-super-admin',
      companyId: 'c1-noor-retail',
      taskId: 'task-101',
      taskCode: 'TSK-0000',
      type: 'file_uploaded',
      titleEn: 'New File Attached',
      titleAr: 'تم رفع مرفق جديد للمهمة',
      messageEn: 'Document "Technical_Specification_v3.pdf" (2.4 MB) was uploaded.',
      messageAr: 'تم إرفاق المستند "Technical_Specification_v3.pdf" (2.4 ميغابايت) بالمهمة.',
      isRead: false,
      actionUrl: '/tasks?taskId=task-101',
      createdAt: getIso(15),
    },
    // Also duplicate essential notifications for Admin user
    {
      id: 'notif-admin-1',
      userId: 'u2-admin',
      companyId: 'c1-noor-retail',
      taskId: 'task-101',
      taskCode: 'TSK-0000',
      type: 'new_task',
      titleEn: 'New Task in your Company',
      titleAr: 'مهمة جديدة في شركتك',
      messageEn: 'Task TSK-0000 created in Al-Noor Retail.',
      messageAr: 'تم إنشاء المهمة TSK-0000 في مجموعة النور للتجزئة.',
      isRead: false,
      actionUrl: '/tasks?taskId=task-101',
      createdAt: getIso(120),
    },
    {
      id: 'notif-admin-2',
      userId: 'u2-admin',
      companyId: 'c1-noor-retail',
      taskId: 'task-103',
      taskCode: 'TSK-0002',
      type: 'task_delayed',
      titleEn: 'Task Delayed in Al-Noor Retail',
      titleAr: 'تأخرت مهمة في مجموعة النور',
      messageEn: 'Task TSK-0002 was delayed due to vendor supply issues.',
      messageAr: 'المهمة TSK-0002 متأخرة بسبب تأخيرات التوريد.',
      isRead: false,
      actionUrl: '/tasks?taskId=task-103',
      createdAt: getIso(60),
    },
    {
      id: 'notif-admin-3',
      userId: 'u2-admin',
      companyId: 'c1-noor-retail',
      taskId: 'task-101',
      taskCode: 'TSK-0000',
      type: 'file_uploaded',
      titleEn: 'Technical Document Attached',
      titleAr: 'مستند فني مرفق',
      messageEn: 'Technical_Specification_v3.pdf was uploaded.',
      messageAr: 'تم رفع الملف Technical_Specification_v3.pdf.',
      isRead: false,
      actionUrl: '/tasks?taskId=task-101',
      createdAt: getIso(15),
    },
  ];

  const dashboardConfigs: UserDashboardConfig[] = [
    // Super Admin: All widgets enabled, all charts enabled, global companies scope
    {
      id: 'cfg-u1-super-admin',
      userId: 'u1-super-admin',
      companyIds: ['all'],
      widgets: [
        { key: 'total_companies', enabled: true, order: 1 },
        { key: 'total_tasks', enabled: true, order: 2 },
        { key: 'pending_tasks', enabled: true, order: 3 },
        { key: 'in_progress_tasks', enabled: true, order: 4 },
        { key: 'delayed_tasks', enabled: true, order: 5 },
        { key: 'completed_tasks', enabled: true, order: 6 },
        { key: 'paused_tasks', enabled: true, order: 7 },
        { key: 'cancelled_tasks', enabled: true, order: 8 },
        { key: 'vip_tasks', enabled: true, order: 9 },
        { key: 'overdue_tasks', enabled: true, order: 10 },
        { key: 'completion_rate', enabled: true, order: 11 },
      ],
      charts: [
        { key: 'tasks_by_company', enabled: true, order: 1 },
        { key: 'tasks_by_status', enabled: true, order: 2 },
        { key: 'tasks_by_priority', enabled: true, order: 3 },
        { key: 'tasks_by_user', enabled: true, order: 4 },
        { key: 'tasks_over_time', enabled: true, order: 5 },
      ],
      showRecentTasks: true,
      updatedAt: new Date().toISOString(),
      updatedBy: 'u1-super-admin',
    },
    // Manager B (Sara - Company Admin): Company A + B (Retail + TechSphere), Tasks, Priority Chart, etc.
    {
      id: 'cfg-u2-admin',
      userId: 'u2-admin',
      companyIds: ['c1-noor-retail', 'c3-techsphere'],
      widgets: [
        { key: 'total_tasks', enabled: true, order: 1 },
        { key: 'in_progress_tasks', enabled: true, order: 2 },
        { key: 'pending_tasks', enabled: true, order: 3 },
        { key: 'delayed_tasks', enabled: true, order: 4 },
        { key: 'completed_tasks', enabled: true, order: 5 },
        { key: 'vip_tasks', enabled: true, order: 6 },
        { key: 'overdue_tasks', enabled: true, order: 7 },
        { key: 'completion_rate', enabled: true, order: 8 },
        { key: 'total_companies', enabled: true, order: 9 },
        { key: 'paused_tasks', enabled: false, order: 10 },
        { key: 'cancelled_tasks', enabled: false, order: 11 },
      ],
      charts: [
        { key: 'tasks_by_priority', enabled: true, order: 1 },
        { key: 'tasks_by_status', enabled: true, order: 2 },
        { key: 'tasks_by_company', enabled: true, order: 3 },
        { key: 'tasks_over_time', enabled: true, order: 4 },
        { key: 'tasks_by_user', enabled: false, order: 5 },
      ],
      showRecentTasks: true,
      updatedAt: new Date().toISOString(),
      updatedBy: 'u1-super-admin',
    },
    // Manager A (Faisal - Department Manager): Company A only, Total Tasks, Status Chart, Completion Rate
    {
      id: 'cfg-u3-manager',
      userId: 'u3-manager',
      companyIds: ['c1-noor-retail'],
      widgets: [
        { key: 'total_tasks', enabled: true, order: 1 },
        { key: 'completion_rate', enabled: true, order: 2 },
        { key: 'in_progress_tasks', enabled: true, order: 3 },
        { key: 'pending_tasks', enabled: true, order: 4 },
        { key: 'delayed_tasks', enabled: true, order: 5 },
        { key: 'completed_tasks', enabled: true, order: 6 },
        { key: 'total_companies', enabled: false, order: 7 },
        { key: 'paused_tasks', enabled: false, order: 8 },
        { key: 'cancelled_tasks', enabled: false, order: 9 },
        { key: 'vip_tasks', enabled: false, order: 10 },
        { key: 'overdue_tasks', enabled: false, order: 11 },
      ],
      charts: [
        { key: 'tasks_by_status', enabled: true, order: 1 },
        { key: 'tasks_by_priority', enabled: false, order: 2 },
        { key: 'tasks_by_company', enabled: false, order: 3 },
        { key: 'tasks_by_user', enabled: false, order: 4 },
        { key: 'tasks_over_time', enabled: false, order: 5 },
      ],
      showRecentTasks: true,
      updatedAt: new Date().toISOString(),
      updatedBy: 'u1-super-admin',
    },
  ];

  return {
    companies,
    users,
    roles,
    permissions,
    userRoles,
    rolePermissions,
    userCompanies,
    taskStatuses,
    taskPriorities,
    tasks: enrichedTasks,
    companyFiles,
    customFields,
    customFieldValues: [],
    notifications,
    auditLogs,
    dashboardConfigs,
    systemAbout: {
      aboutTitleAr: 'منظومة إدارة الشركات والعمليات المؤسسية',
      aboutTitleEn: 'Holding Enterprise Multi-Tenant OS',
      aboutDescriptionAr: 'منصة رقمية موحدة متقدمة لحوكمة مجموعات الشركات، إدارة الصلاحيات الدقيقة، تنظيم مسارات العمل والمهام، والتقارير التنفيذية بأعلى معايير الأمان والامتثال المؤسسي.',
      aboutDescriptionEn: 'A unified enterprise SaaS platform for managing corporate groups, granular permissions, automated workflows, executive reporting, and cross-company governance.',
      copyrightTextAr: 'حقوق النظام محفوظة للمهندس علي أحمد عنيد',
      copyrightTextEn: 'System Rights Reserved to Engineer Ali Ahmed Aneed',
      developerNameAr: 'المهندس علي أحمد عنيد',
      developerNameEn: 'Eng. Ali Ahmed Aneed',
      systemVersion: 'v2.5.0 Enterprise Release',
      licenseType: 'Enterprise Proprietary Commercial License',
      supportEmail: 'allawi.aneed95@gmail.com',
      updatedAt: new Date().toISOString(),
      updatedBy: 'u1-super-admin',
    },
  };
}
